root - INFO - Бот запускается
2019-09-07 18:52:41,510 - INFO - Бот запускается
2019-09-07 18:53:48,484 - INFO - Бот запускается
2019-09-07 18:53:55,719 - INFO - Send email to the customer
2019-09-07 18:59:59,949 - INFO - Бот запускается
2019-09-07 19:00:15,205 - INFO - Send answer to the client
2019-09-07 19:01:55,190 - INFO - Бот запускается
2019-09-07 19:02:00,518 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Program Files\Python37\lib\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:/Users/Philipesko/PycharmProjects/LearningPython14/megabot/bot.py", line 17, in talk_to_me
    update.message.reply_text(user_text)
  File "C:\Program Files\Python37\lib\site-packages\telegram\message.py", line 478, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 258, in send_message
    timeout=timeout, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "C:\Program Files\Python37\lib\site-packages\telegram\utils\request.py", line 325, in post
    body=json.dumps(data).encode('utf-8'),
  File "C:\Program Files\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
2019-09-07 19:02:06,887 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Program Files\Python37\lib\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:/Users/Philipesko/PycharmProjects/LearningPython14/megabot/bot.py", line 17, in talk_to_me
    update.message.reply_text(user_text)
  File "C:\Program Files\Python37\lib\site-packages\telegram\message.py", line 478, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 258, in send_message
    timeout=timeout, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "C:\Program Files\Python37\lib\site-packages\telegram\utils\request.py", line 325, in post
    body=json.dumps(data).encode('utf-8'),
  File "C:\Program Files\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
2019-09-07 19:02:36,832 - INFO - Send answer to the client
2019-09-07 19:02:38,893 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\telegram\ext\dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Program Files\Python37\lib\site-packages\telegram\ext\handler.py", line 120, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:/Users/Philipesko/PycharmProjects/LearningPython14/megabot/bot.py", line 17, in talk_to_me
    update.message.reply_text(user_text)
  File "C:\Program Files\Python37\lib\site-packages\telegram\message.py", line 478, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 258, in send_message
    timeout=timeout, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\telegram\bot.py", line 123, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "C:\Program Files\Python37\lib\site-packages\telegram\utils\request.py", line 325, in post
    body=json.dumps(data).encode('utf-8'),
  File "C:\Program Files\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
2019-09-07 19:03:24,076 - INFO - Бот запускается
2019-09-07 19:03:31,500 - INFO - Receive message text from client:привет
2019-09-07 19:03:35,355 - INFO - Send answer to the client
2019-09-07 19:06:06,872 - INFO - Бот запускается
2019-09-07 19:06:14,096 - INFO - Receive message text from client:привет.
